default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: villaridge
  password: 053193
  host: localhost

development:
  <<: *default
  database: packing-list-app_development

test:
  <<: *default
  database: packing-list-app_test

production:
  <<: *default
  database: packing-list-app_production
